/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package triki;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mac
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Tablero3x3.setVisible(false);
        Tablero4x4.setVisible(false);
        Tablero5x5.setVisible(false);
    }

    Juego juego = new Juego();

    int auxiliarJugador = 1;
    int cantidadDeMovimientos = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreJugadorUno = new javax.swing.JTextField();
        NombreJugadorDos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FichaJugadorUno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FichaJugadorDos = new javax.swing.JTextField();
        IniciarJuego = new javax.swing.JButton();
        ColorJugadorUno = new javax.swing.JComboBox<>();
        ColorJugadorDos = new javax.swing.JComboBox<>();
        TipoDeTablero = new javax.swing.JComboBox<>();
        Tablero3x3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        T3300 = new javax.swing.JLabel();
        T3301 = new javax.swing.JLabel();
        T3302 = new javax.swing.JLabel();
        T3310 = new javax.swing.JLabel();
        T3311 = new javax.swing.JLabel();
        T3312 = new javax.swing.JLabel();
        T3320 = new javax.swing.JLabel();
        T3321 = new javax.swing.JLabel();
        T3322 = new javax.swing.JLabel();
        Tablero4x4 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        T4400 = new javax.swing.JLabel();
        T4401 = new javax.swing.JLabel();
        T4402 = new javax.swing.JLabel();
        T4403 = new javax.swing.JLabel();
        T4410 = new javax.swing.JLabel();
        T4411 = new javax.swing.JLabel();
        T4412 = new javax.swing.JLabel();
        T4413 = new javax.swing.JLabel();
        T4420 = new javax.swing.JLabel();
        T4421 = new javax.swing.JLabel();
        T4422 = new javax.swing.JLabel();
        T4423 = new javax.swing.JLabel();
        T4430 = new javax.swing.JLabel();
        T4431 = new javax.swing.JLabel();
        T4432 = new javax.swing.JLabel();
        T4433 = new javax.swing.JLabel();
        Tablero5x5 = new javax.swing.JPanel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        T5500 = new javax.swing.JLabel();
        T5501 = new javax.swing.JLabel();
        T5502 = new javax.swing.JLabel();
        T5503 = new javax.swing.JLabel();
        T5504 = new javax.swing.JLabel();
        T5510 = new javax.swing.JLabel();
        T5511 = new javax.swing.JLabel();
        T5512 = new javax.swing.JLabel();
        T5513 = new javax.swing.JLabel();
        T5514 = new javax.swing.JLabel();
        T5520 = new javax.swing.JLabel();
        T5521 = new javax.swing.JLabel();
        T5522 = new javax.swing.JLabel();
        T5523 = new javax.swing.JLabel();
        T5524 = new javax.swing.JLabel();
        T5530 = new javax.swing.JLabel();
        T5531 = new javax.swing.JLabel();
        T5532 = new javax.swing.JLabel();
        T5533 = new javax.swing.JLabel();
        T5534 = new javax.swing.JLabel();
        T5540 = new javax.swing.JLabel();
        T5541 = new javax.swing.JLabel();
        T5542 = new javax.swing.JLabel();
        T5543 = new javax.swing.JLabel();
        T5544 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de Triquitraque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 0, -1, 359));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 359));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Jugador #1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Jugador #2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 26, -1, -1));

        NombreJugadorUno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(NombreJugadorUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 180, -1));

        NombreJugadorDos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(NombreJugadorDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 75, 180, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Color");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 114, 99, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Color");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 114, 99, -1));

        FichaJugadorUno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(FichaJugadorUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 180, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ficha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 201, 99, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ficha");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 201, 99, -1));

        FichaJugadorDos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(FichaJugadorDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 243, 180, -1));

        IniciarJuego.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        IniciarJuego.setText("Iniciar");
        IniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 42, 300, -1));

        ColorJugadorUno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ColorJugadorUno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Verde", "Negro", "Azul" }));
        ColorJugadorUno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ColorJugadorUnoItemStateChanged(evt);
            }
        });
        ColorJugadorUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorJugadorUnoActionPerformed(evt);
            }
        });
        jPanel1.add(ColorJugadorUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        ColorJugadorDos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ColorJugadorDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Verde", "Negro", "Azul" }));
        ColorJugadorDos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ColorJugadorDosItemStateChanged(evt);
            }
        });
        ColorJugadorDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorJugadorDosActionPerformed(evt);
            }
        });
        jPanel1.add(ColorJugadorDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 170, -1));

        TipoDeTablero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TipoDeTablero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar tipo de tablero", "3 x 3", "4 x 4", "5 x 5" }));
        TipoDeTablero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TipoDeTableroItemStateChanged(evt);
            }
        });
        TipoDeTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeTableroActionPerformed(evt);
            }
        });
        jPanel1.add(TipoDeTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 7, 300, -1));

        Tablero3x3.setBackground(new java.awt.Color(255, 255, 255));
        Tablero3x3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero3x3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 11, 245));
        Tablero3x3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 300, 10));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero3x3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 11, 245));
        Tablero3x3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 10));

        T3300.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3300.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3300.setToolTipText("Poner ficha");
        T3300.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3300MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3300, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        T3301.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3301.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3301.setToolTipText("Poner ficha");
        T3301.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3301MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3301, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 60));

        T3302.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3302.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3302.setToolTipText("Poner ficha");
        T3302.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3302MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3302, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 80, 60));

        T3310.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3310.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3310.setToolTipText("Poner ficha");
        T3310.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3310MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3310, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 60));

        T3311.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3311.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3311.setToolTipText("Poner ficha");
        T3311.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3311MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3311, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 60));

        T3312.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3312.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3312.setToolTipText("Poner ficha");
        T3312.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3312MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3312, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 80, 60));

        T3320.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3320.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3320.setToolTipText("Poner ficha");
        T3320.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3320MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3320, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 70));

        T3321.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3321.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3321.setToolTipText("Poner ficha");
        T3321.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3321MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3321, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, 60));

        T3322.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T3322.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3322.setToolTipText("Poner ficha");
        T3322.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T3322MouseClicked(evt);
            }
        });
        Tablero3x3.add(T3322, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, 60));

        jPanel1.add(Tablero3x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 75, 300, 245));

        Tablero4x4.setBackground(new java.awt.Color(255, 255, 255));
        Tablero4x4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero4x4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 10, 245));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero4x4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 10, 245));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero4x4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 10, 245));
        Tablero4x4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 10));
        Tablero4x4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 10));
        Tablero4x4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 10));

        T4400.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4400.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4400.setToolTipText("Poner ficha");
        T4400.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4400MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4400, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        T4401.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4401.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4401.setToolTipText("Poner ficha");
        T4401.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4401MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4401, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 60, 40));

        T4402.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4402.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4402.setToolTipText("Poner ficha");
        T4402.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4402MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4402, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 60, 40));

        T4403.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4403.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4403.setToolTipText("Poner ficha");
        T4403.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4403MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4403, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 40));

        T4410.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4410.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4410.setToolTipText("Poner ficha");
        T4410.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4410MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4410, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 40));

        T4411.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4411.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4411.setToolTipText("Poner ficha");
        T4411.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4411MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4411, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 40));

        T4412.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4412.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4412.setToolTipText("Poner ficha");
        T4412.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4412MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4412, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 40));

        T4413.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4413.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4413.setToolTipText("Poner ficha");
        T4413.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4413MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4413, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 50, 40));

        T4420.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4420.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4420.setToolTipText("Poner ficha");
        T4420.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4420MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4420, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 40));

        T4421.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4421.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4421.setToolTipText("Poner ficha");
        T4421.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4421MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4421, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 40));

        T4422.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4422.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4422.setToolTipText("Poner ficha");
        T4422.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4422MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4422, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 60, 40));

        T4423.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4423.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4423.setToolTipText("Poner ficha");
        T4423.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4423MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4423, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 50, 40));

        T4430.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4430.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4430.setToolTipText("Poner ficha");
        T4430.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4430MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4430, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 40));

        T4431.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4431.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4431.setToolTipText("Poner ficha");
        T4431.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4431MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4431, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 40));

        T4432.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4432.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4432.setToolTipText("Poner ficha");
        T4432.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4432MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4432, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 60, 40));

        T4433.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T4433.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4433.setToolTipText("Poner ficha");
        T4433.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T4433MouseClicked(evt);
            }
        });
        Tablero4x4.add(T4433, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 50, 40));

        jPanel1.add(Tablero4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 75, 300, 245));

        Tablero5x5.setBackground(new java.awt.Color(255, 255, 255));
        Tablero5x5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero5x5.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 10, 245));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero5x5.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 10, 245));

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero5x5.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 10, 245));

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Tablero5x5.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 10, 245));
        Tablero5x5.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 10));
        Tablero5x5.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 10));
        Tablero5x5.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 300, 10));
        Tablero5x5.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 10));

        T5500.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5500.setToolTipText("Poner ficha");
        T5500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5500MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5500, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        T5501.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5501.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5501.setToolTipText("Poner ficha");
        T5501.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5501MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5501, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 50, 40));

        T5502.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5502.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5502.setToolTipText("Poner ficha");
        T5502.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5502MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5502, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 50, 40));

        T5503.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5503.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5503.setToolTipText("Poner ficha");
        T5503.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5503MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5503, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 40, 40));

        T5504.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5504.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5504.setToolTipText("Poner ficha");
        T5504.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5504MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5504, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 40));

        T5510.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5510.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5510.setToolTipText("Poner ficha");
        T5510.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5510MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5510, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 40, 40));

        T5511.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5511.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5511.setToolTipText("Poner ficha");
        T5511.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5511MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5511, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, 40));

        T5512.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5512.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5512.setToolTipText("Poner ficha");
        T5512.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5512MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5512, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 50, 40));

        T5513.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5513.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5513.setToolTipText("Poner ficha");
        T5513.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5513MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5513, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 40, 40));

        T5514.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5514.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5514.setToolTipText("Poner ficha");
        T5514.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5514MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5514, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 40));

        T5520.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5520.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5520.setToolTipText("Poner ficha");
        T5520.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5520MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5520, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 40, 40));

        T5521.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5521.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5521.setToolTipText("Poner ficha");
        T5521.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5521MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5521, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 40, 40));

        T5522.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5522.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5522.setToolTipText("Poner ficha");
        T5522.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5522MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5522, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 50, 40));

        T5523.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5523.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5523.setToolTipText("Poner ficha");
        T5523.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5523MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5523, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 50, 40));

        T5524.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5524.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5524.setToolTipText("Poner ficha");
        T5524.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5524MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5524, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, 40));

        T5530.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5530.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5530.setToolTipText("Poner ficha");
        T5530.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5530MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5530, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 40));

        T5531.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5531.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5531.setToolTipText("Poner ficha");
        T5531.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5531MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5531, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, 40));

        T5532.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5532.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5532.setToolTipText("Poner ficha");
        T5532.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5532MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5532, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 50, 40));

        T5533.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5533.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5533.setToolTipText("Poner ficha");
        T5533.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5533MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5533, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 40, 40));

        T5534.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5534.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5534.setToolTipText("Poner ficha");
        T5534.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5534MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5534, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 40, 40));

        T5540.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5540.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5540.setToolTipText("Poner ficha");
        T5540.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5540MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5540, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 30, 40));

        T5541.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5541.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5541.setToolTipText("Poner ficha");
        T5541.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5541MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5541, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 40, 40));

        T5542.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5542.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5542.setToolTipText("Poner ficha");
        T5542.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5542MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5542, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 50, 40));

        T5543.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5543.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5543.setToolTipText("Poner ficha");
        T5543.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5543MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5543, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 40, 40));

        T5544.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        T5544.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5544.setToolTipText("Poner ficha");
        T5544.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T5544MouseClicked(evt);
            }
        });
        Tablero5x5.add(T5544, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 40, 40));

        jPanel1.add(Tablero5x5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 75, 300, 245));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorJugadorDosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ColorJugadorDosItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_ColorJugadorDosItemStateChanged

    private void ColorJugadorDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorJugadorDosActionPerformed

    }//GEN-LAST:event_ColorJugadorDosActionPerformed

    private void IniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarJuegoActionPerformed
        // TODO add your handling code here:
        if (NombreJugadorUno.getText().equals("")
                || NombreJugadorDos.getText().equals("")
                || NombreJugadorUno.getText().equals(NombreJugadorDos.getText())) {
            JOptionPane.showMessageDialog(null, "¡Los nombres de los jugadores son requeridos y diferentes!");
        } else {
            if (ColorJugadorUno.getSelectedIndex() == ColorJugadorDos.getSelectedIndex()) {
                JOptionPane.showMessageDialog(null, "¡Los colores de los jugadores son requeridos y diferentes!");
            } else {
                if (FichaJugadorUno.getText().equals("")
                        || FichaJugadorDos.getText().equals("")
                        || FichaJugadorUno.getText().equals(FichaJugadorDos.getText())) {
                    JOptionPane.showMessageDialog(null, "¡Las ficha de los jugadores son requeridas y diferentes!");
                } else {
                    if (TipoDeTablero.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(null, "¡El tipo de tablero es requerido!");
                    } else {
                        Jugador jugadorUno = new Jugador(
                                NombreJugadorUno.getText(),
                                ColorJugadorUno.getItemAt(ColorJugadorUno.getSelectedIndex()),
                                FichaJugadorUno.getText()
                        );
                        Jugador jugadorDos = new Jugador(
                                NombreJugadorDos.getText(),
                                ColorJugadorDos.getItemAt(ColorJugadorDos.getSelectedIndex()),
                                FichaJugadorDos.getText()
                        );

                        String tipoDeTablero = TipoDeTablero.getItemAt(TipoDeTablero.getSelectedIndex());
                        String tamañoTablero[] = tipoDeTablero.split(" x ");

                        int dimensionTablero[][] = new int[Integer.parseInt(tamañoTablero[0])][Integer.parseInt(tamañoTablero[1])];

                        Tablero tablero = new Tablero(dimensionTablero);
                        Jugador jugadores[] = {jugadorUno, jugadorDos};

                        juego.iniciarPartida(jugadores, tablero);

                        enabledInicioDePartida();

                        JOptionPane.showMessageDialog(null, "¡Partida iniciada!");
                    }
                }
            }
        }
    }//GEN-LAST:event_IniciarJuegoActionPerformed

    private void TipoDeTableroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoDeTableroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeTableroItemStateChanged

    private void TipoDeTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeTableroActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String tipoDeTablero = TipoDeTablero.getItemAt(TipoDeTablero.getSelectedIndex());
        if (tipoDeTablero.equals(TipoDeTablero.getItemAt(1))) {
            Tablero3x3.setVisible(true);
            Tablero4x4.setVisible(false);
            Tablero5x5.setVisible(false);
            cantidadDeMovimientos = 9;
        } else if (tipoDeTablero.equals(TipoDeTablero.getItemAt(2))) {
            Tablero3x3.setVisible(false);
            Tablero4x4.setVisible(true);
            Tablero5x5.setVisible(false);
            cantidadDeMovimientos = 16;
        } else if (tipoDeTablero.equals(TipoDeTablero.getItemAt(3))) {
            Tablero3x3.setVisible(false);
            Tablero4x4.setVisible(false);
            Tablero5x5.setVisible(true);
            cantidadDeMovimientos = 25;
        } else {
            cantidadDeMovimientos = 0;
            Tablero3x3.setVisible(false);
            Tablero4x4.setVisible(false);
            Tablero5x5.setVisible(false);
        }
    }//GEN-LAST:event_TipoDeTableroActionPerformed

    private void ColorJugadorUnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ColorJugadorUnoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorJugadorUnoItemStateChanged

    private void ColorJugadorUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorJugadorUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorJugadorUnoActionPerformed

    private void T3300MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3300MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 0);
    }//GEN-LAST:event_T3300MouseClicked

    private void T3301MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3301MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 1);
    }//GEN-LAST:event_T3301MouseClicked

    private void T3302MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3302MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 2);
    }//GEN-LAST:event_T3302MouseClicked

    private void T3310MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3310MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 0);
    }//GEN-LAST:event_T3310MouseClicked

    private void T3311MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3311MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 1);
    }//GEN-LAST:event_T3311MouseClicked

    private void T3312MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3312MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 2);
    }//GEN-LAST:event_T3312MouseClicked

    private void T3320MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3320MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 0);
    }//GEN-LAST:event_T3320MouseClicked

    private void T3321MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3321MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 1);
    }//GEN-LAST:event_T3321MouseClicked

    private void T3322MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T3322MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 2);
    }//GEN-LAST:event_T3322MouseClicked

    private void T4400MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4400MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 0);
    }//GEN-LAST:event_T4400MouseClicked

    private void T4401MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4401MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 1);
    }//GEN-LAST:event_T4401MouseClicked

    private void T4402MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4402MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 2);
    }//GEN-LAST:event_T4402MouseClicked

    private void T4403MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4403MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 3);
    }//GEN-LAST:event_T4403MouseClicked

    private void T4410MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4410MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 0);
    }//GEN-LAST:event_T4410MouseClicked

    private void T4411MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4411MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 1);
    }//GEN-LAST:event_T4411MouseClicked

    private void T4412MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4412MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 2);
    }//GEN-LAST:event_T4412MouseClicked

    private void T4413MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4413MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 3);
    }//GEN-LAST:event_T4413MouseClicked

    private void T4420MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4420MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 0);
    }//GEN-LAST:event_T4420MouseClicked

    private void T4421MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4421MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 1);
    }//GEN-LAST:event_T4421MouseClicked

    private void T4422MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4422MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 2);
    }//GEN-LAST:event_T4422MouseClicked

    private void T4423MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4423MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 3);
    }//GEN-LAST:event_T4423MouseClicked

    private void T4430MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4430MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 0);
    }//GEN-LAST:event_T4430MouseClicked

    private void T4431MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4431MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 1);
    }//GEN-LAST:event_T4431MouseClicked

    private void T4432MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4432MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 2);
    }//GEN-LAST:event_T4432MouseClicked

    private void T4433MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T4433MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 3);
    }//GEN-LAST:event_T4433MouseClicked

    private void T5500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5500MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 0);
    }//GEN-LAST:event_T5500MouseClicked

    private void T5501MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5501MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 1);
    }//GEN-LAST:event_T5501MouseClicked

    private void T5502MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5502MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 2);
    }//GEN-LAST:event_T5502MouseClicked

    private void T5503MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5503MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 3);
    }//GEN-LAST:event_T5503MouseClicked

    private void T5504MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5504MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 0, 4);
    }//GEN-LAST:event_T5504MouseClicked

    private void T5510MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5510MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 0);
    }//GEN-LAST:event_T5510MouseClicked

    private void T5511MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5511MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 1);
    }//GEN-LAST:event_T5511MouseClicked

    private void T5512MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5512MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 2);
    }//GEN-LAST:event_T5512MouseClicked

    private void T5513MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5513MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 3);
    }//GEN-LAST:event_T5513MouseClicked

    private void T5514MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5514MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 1, 4);
    }//GEN-LAST:event_T5514MouseClicked

    private void T5520MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5520MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 0);
    }//GEN-LAST:event_T5520MouseClicked

    private void T5521MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5521MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 1);
    }//GEN-LAST:event_T5521MouseClicked

    private void T5522MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5522MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 2);
    }//GEN-LAST:event_T5522MouseClicked

    private void T5523MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5523MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 3);
    }//GEN-LAST:event_T5523MouseClicked

    private void T5524MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5524MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 2, 4);
    }//GEN-LAST:event_T5524MouseClicked

    private void T5530MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5530MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 0);
    }//GEN-LAST:event_T5530MouseClicked

    private void T5531MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5531MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 1);
    }//GEN-LAST:event_T5531MouseClicked

    private void T5532MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5532MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 2);
    }//GEN-LAST:event_T5532MouseClicked

    private void T5533MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5533MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 3);
    }//GEN-LAST:event_T5533MouseClicked

    private void T5534MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5534MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 3, 4);
    }//GEN-LAST:event_T5534MouseClicked

    private void T5540MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5540MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 4, 0);
    }//GEN-LAST:event_T5540MouseClicked

    private void T5541MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5541MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 4, 1);
    }//GEN-LAST:event_T5541MouseClicked

    private void T5542MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5542MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 4, 2);
    }//GEN-LAST:event_T5542MouseClicked

    private void T5543MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5543MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 4, 3);
    }//GEN-LAST:event_T5543MouseClicked

    private void T5544MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T5544MouseClicked
        // TODO add your handling code here:
        JLabel temp = ((javax.swing.JLabel) evt.getSource());
        moverFicha(temp, 4, 4);
    }//GEN-LAST:event_T5544MouseClicked

    public void moverFicha(JLabel label, int fila, int columna) {
        String salida = juego.manejarEntradaUsuario(fila, columna, auxiliarJugador);

        if (salida.contains("mover")) {
            JOptionPane.showMessageDialog(null, salida);
            return;
        }

        cantidadDeMovimientos--;
        label.setForeground(getColor(juego.getJugadores()[auxiliarJugador - 1].getColor()));
        label.setText(String.valueOf(juego.getJugadores()[auxiliarJugador - 1].getFicha()));

        if (salida.contains("Gana")) {
            JOptionPane.showMessageDialog(null, salida);
            ultimoMovimeinto();
            return;
        }
        if (salida.contains("empate") && cantidadDeMovimientos == 0) {
            JOptionPane.showMessageDialog(null, salida);
            ultimoMovimeinto();
            return;
        }
        if (salida.contains("turno")) {
            if (auxiliarJugador == 1) {
                auxiliarJugador = 2;
            } else {
                auxiliarJugador = 1;
            }
            JOptionPane.showMessageDialog(null, salida);
        }
    }

    public void ultimoMovimeinto() {
        /*if (respuestaDeOpcionesDeJuego == JOptionPane.YES_OPTION) {
            try {
                String java = System.getProperty("java.home") + "/bin/java";
                String currentJar = new File(Principal.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getPath();
                ProcessBuilder builder = new ProcessBuilder(java, "-jar", currentJar);
                builder.start();
                System.exit(0);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "¡Juego finalizado! Para jugar de nuevo iniciar de nuevo la aplicación.");
            System.exit(0);
        }*/
        JOptionPane.showMessageDialog(null, "¡Juego finalizado! Para jugar de nuevo iniciar de nuevo la aplicación.");
        System.exit(0);
    }

    public void enabledInicioDePartida() {
        NombreJugadorUno.setEnabled(false);
        ColorJugadorUno.setEnabled(false);
        FichaJugadorUno.setEnabled(false);

        NombreJugadorDos.setEnabled(false);
        ColorJugadorDos.setEnabled(false);
        FichaJugadorDos.setEnabled(false);

        TipoDeTablero.setEnabled(false);

        IniciarJuego.setEnabled(false);
    }

    public Color getColor(String color) {
        switch (color) {
            case "Rojo":
                return Color.RED;
            case "Verde":
                return Color.GREEN;
            case "Negro":
                return Color.BLACK;

            default:
                return Color.BLUE;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ColorJugadorDos;
    private javax.swing.JComboBox<String> ColorJugadorUno;
    private javax.swing.JTextField FichaJugadorDos;
    private javax.swing.JTextField FichaJugadorUno;
    private javax.swing.JButton IniciarJuego;
    private javax.swing.JTextField NombreJugadorDos;
    private javax.swing.JTextField NombreJugadorUno;
    private javax.swing.JLabel T3300;
    private javax.swing.JLabel T3301;
    private javax.swing.JLabel T3302;
    private javax.swing.JLabel T3310;
    private javax.swing.JLabel T3311;
    private javax.swing.JLabel T3312;
    private javax.swing.JLabel T3320;
    private javax.swing.JLabel T3321;
    private javax.swing.JLabel T3322;
    private javax.swing.JLabel T4400;
    private javax.swing.JLabel T4401;
    private javax.swing.JLabel T4402;
    private javax.swing.JLabel T4403;
    private javax.swing.JLabel T4410;
    private javax.swing.JLabel T4411;
    private javax.swing.JLabel T4412;
    private javax.swing.JLabel T4413;
    private javax.swing.JLabel T4420;
    private javax.swing.JLabel T4421;
    private javax.swing.JLabel T4422;
    private javax.swing.JLabel T4423;
    private javax.swing.JLabel T4430;
    private javax.swing.JLabel T4431;
    private javax.swing.JLabel T4432;
    private javax.swing.JLabel T4433;
    private javax.swing.JLabel T5500;
    private javax.swing.JLabel T5501;
    private javax.swing.JLabel T5502;
    private javax.swing.JLabel T5503;
    private javax.swing.JLabel T5504;
    private javax.swing.JLabel T5510;
    private javax.swing.JLabel T5511;
    private javax.swing.JLabel T5512;
    private javax.swing.JLabel T5513;
    private javax.swing.JLabel T5514;
    private javax.swing.JLabel T5520;
    private javax.swing.JLabel T5521;
    private javax.swing.JLabel T5522;
    private javax.swing.JLabel T5523;
    private javax.swing.JLabel T5524;
    private javax.swing.JLabel T5530;
    private javax.swing.JLabel T5531;
    private javax.swing.JLabel T5532;
    private javax.swing.JLabel T5533;
    private javax.swing.JLabel T5534;
    private javax.swing.JLabel T5540;
    private javax.swing.JLabel T5541;
    private javax.swing.JLabel T5542;
    private javax.swing.JLabel T5543;
    private javax.swing.JLabel T5544;
    private javax.swing.JPanel Tablero3x3;
    private javax.swing.JPanel Tablero4x4;
    private javax.swing.JPanel Tablero5x5;
    private javax.swing.JComboBox<String> TipoDeTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
